### ISSUE TITLE
throws false-positive warnings

### ISSUE THREAD

**Issue by Tomekmularczyk** [Andarist/are-hook-inputs-equal#1]
Hey there 👋 
The code copied from [here](https://github.com/facebook/react/blob/e02086bfcc698d02a41a7785a1027a94dbc88eea/packages/react-reconciler/src/ReactFiberHooks.js#L763-L791) uses an internal `warning` method, it doesn't work the same as `console.warn`(first argument is not a boolean). This makes it print warnings on each render in the development mode.

**Comment by Andarist** [comment]
You are right, gonna release a fix for this in a moment.

**Comment by Andarist** [comment]
Fixed by https://github.com/Andarist/are-hook-inputs-equal/commit/f5b6f4ba002b3cd218ae9c015cb6879186ace78c.

Out of curiosity - how do you plan to use this module?

**Comment by Tomekmularczyk** [comment]
@Andarist I'm working on a solution to fix a bug https://github.com/Tomekmularczyk/react-id-generator/issues/10 and this may be useful :)
